const studentList = [
    {
        id:1,
        first_name:"Evelyn",
        last_name:"Garnam",
        email:"lgarnam0@instagram.com",
        gender:"Female",
        picture:"https://robohash.org/corporisetporro.png?size=50x50&set=set1"
    },
    {
        id:2,
        first_name:"Aranka",
        last_name:"Bryce",
        email:"tbryce1@patch.com",
        gender:"Female",
        picture:"https://robohash.org/eteumrepudiandae.png?size=50x50&set=set1"
    },
    {
        id:3,
        first_name:"Floris",
        last_name:"Shemelt",
        email:"gshemelt2@msu.edu",
        gender:"Male",
        picture:"https://robohash.org/etdoloribuseaque.png?size=50x50&set=set1"
    },
    {
        id:4,
        first_name:"Hector",
        last_name:"Mulvy",
        email:"cmulvy3@ted.com",
        gender:"Male",
        picture:"https://robohash.org/atqueestdicta.png?size=50x50&set=set1"
    },
    {
        id:5,
        first_name:"Martina",
        last_name:"Creamer",
        email:"mcreamer4@microsoft.com",
        gender:"Female",
        picture:"https://robohash.org/laboriosamnesciunthic.png?size=50x50&set=set1"
    },
    {
        id:6,
        first_name:"Maurits",
        last_name:"Badwick",
        email:"kbadwick5@cmu.edu",
        gender:"Male",
        picture:"https://robohash.org/sedsunteum.png?size=50x50&set=set1"
    },
    {
        id:7,
        first_name:"Rahima",
        last_name:"Lumox",
        email:"glumox6@shop-pro.jp",
        gender:"Female",
        picture:"https://robohash.org/estaliasconsequatur.png?size=50x50&set=set1"
    },
    {
        id:8,
        first_name:"Sandra",
        last_name:"Twohig",
        email:"jtwohig7@biblegateway.com",
        gender:"Female",
        picture:"https://robohash.org/corporisveritatisomnis.png?size=50x50&set=set1"
    },
    {
        id:9,
        first_name:"Wietske",
        last_name:"Totterdill",
        email:"ftotterdill8@hhs.gov",
        gender:"Female",
        picture:"https://robohash.org/quiasintut.png?size=50x50&set=set1"
    },
    {
        id:10,
        first_name:"Storm",
        last_name:"Pasquale",
        email:"epasquale9@microsoft.com",
        gender:"Male",
        picture:"https://robohash.org/molestiaepariaturnihil.png?size=50x50&set=set1"}
    ]

    export default studentList;